#!/usr/bin/env python
# -*- coding: utf-8 -*-

from icalendar import Calendar
from datetime import datetime
import requests
import pytz


def get_datetimes_array(ics_file):
	''' 
		Gets an ics Calendar file 
		Returns a sorted array of the start dates of the events 
	'''
	g = open(ics_file,'rb')
	ical = Calendar.from_ical(g.read())
	datetimes = []
	for component in ical.walk():
	    if component.name == 'VEVENT':
	        for item in component.sorted_items():
	            if item[0] == 'DTSTART':
	            	datetimes.append(item[1].dt)
	g.close()

	# uncomment the line below if you want to debug like there is a suspension right now
	datetimes.append(datetime.utcnow().replace(second=0, microsecond=0, tzinfo = pytz.utc))

	return sorted(datetimes)

def yo_all(api_token):
	return requests.post("http://api.justyo.co/yoall/", data={'api_token': api_token})


def check_if_parking_suspend_now(suspends_datetimes, api_token):
	'''
		suspends_datetimes - an array of datetime objects
		api_token - the api token of the Yo username that sends the Yo to all subscribers
	'''
	# go over the array every minute and see if a parking suspension starts now
	upcoming_suspend = suspends_datetimes[0]
	stipped_seconds_now = datetime.utcnow().replace(second=0, microsecond=0, tzinfo=pytz.utc) #  we make sure to strip seconds to comparing every minute will work
	if upcoming_suspend == stipped_seconds_now:
		response = yo_all(api_token)  # found a parking suspension date! sends Yo to all ALTERNATESIDEPARKING subscribers!
		print response  


the_nyc_parking_suspends_datetimes = get_datetimes_array('test.ics')  # got this from the DOT
the_nyc_parkingon_token = 'c6b70d4b-0dd3-c5a8-8082-f65e8f723ce3'  # this token is generated by contacting us at contact@justyo.co or http://bit.ly/yoapi
check_if_parking_suspend_now(the_nyc_parking_suspends_datetimes, the_nyc_parkingon_token)  # the_nyc_parkingon_token sends a Yo as ALTERNATESIDEPARKING
